name: CI

on:
  push:
  pull_request:

jobs:
  build-test-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest -q
      - name: Build dataset and features
        run: |
          python src/data/make_dataset.py
          python src/features/build_features.py
      - name: Train and evaluate
        run: |
          python src/models/train.py
          python src/models/evaluate.py
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-reports
          path: |
            models/model.joblib
            reports/**
